-- ============================================================
-- Fix: nova versão de contrato (editar) salta o código global
-- ============================================================
-- Bug: `codigo` é BIGINT GENERATED BY DEFAULT AS IDENTITY — um único
-- contador para toda a tabela. `criar_versao_contrato_renting` nunca
-- incluía `codigo` no INSERT, por isso cada edição (troca de viatura,
-- datas, etc.) gerava uma versão nova com um código TOTALMENTE novo em
-- vez de continuar o mesmo contrato — e a versão antiga (com o código
-- correcto) ficava escondida da listagem por estar `substituido_em`.
-- Resultado visível: a listagem "salta" números sempre que um contrato
-- é editado, porque o código antigo não aparece mais em lado nenhum
-- (só no separador de Histórico dessa versão específica) e o novo
-- código roubado ao contador global nunca mais é reutilizado.
--
-- Fix: a nova versão herda o `codigo` da versão anterior — o contrato
-- mantém o mesmo número visível ao longo de todas as edições, só a
-- badge de versão (v2, v3, ...) muda. Só contratos genuinamente novos
-- (primeira versão) ou renovações (`renovar_contrato_renting`, que
-- continua a gerar código novo de propósito — é um contrato/mês novo)
-- consomem o contador global.
--
-- A UNIQUE (org_id, codigo) tem de deixar de ser total — com herança de
-- código, várias versões da MESMA cadeia partilham código (só uma fica
-- activa de cada vez). Passa a UNIQUE parcial: só entre versões activas
-- (substituido_em IS NULL, deleted_at IS NULL).
-- ============================================================

ALTER TABLE public.contratos_renting
  DROP CONSTRAINT IF EXISTS contratos_renting_codigo_org_unique;

CREATE UNIQUE INDEX IF NOT EXISTS contratos_renting_codigo_org_active_idx
  ON public.contratos_renting (org_id, codigo)
  WHERE deleted_at IS NULL AND substituido_em IS NULL;

COMMENT ON INDEX public.contratos_renting_codigo_org_active_idx IS
  'Código único só entre versões activas — versões substituídas da mesma '
  'cadeia partilham código de propósito (ver 20260714130000).';

CREATE OR REPLACE FUNCTION public.criar_versao_contrato_renting(
  p_contrato_id uuid,
  p_motivo      text
) RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_old             contratos_renting%ROWTYPE;
  v_new_id          uuid;
  v_user_id         uuid := auth.uid();
BEGIN
  SELECT * INTO v_old
    FROM public.contratos_renting
   WHERE id = p_contrato_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Contrato % não encontrado.', p_contrato_id;
  END IF;

  IF v_old.deleted_at IS NOT NULL THEN
    RAISE EXCEPTION 'Não podes versionar um contrato eliminado.';
  END IF;

  IF v_old.substituido_em IS NOT NULL THEN
    RAISE EXCEPTION 'Este contrato já foi substituído. Versiona a versão actual.';
  END IF;

  IF v_old.estado_financeiro = 'facturado' THEN
    RAISE EXCEPTION 'Não podes versionar um contrato facturado. Anula a factura primeiro.';
  END IF;

  IF v_old.org_id <> get_current_org_id() THEN
    RAISE EXCEPTION 'Sem permissão sobre este contrato.';
  END IF;

  -- 1) Marca a antiga como substituída PRIMEIRO. Sai do espaço de
  --    unicidade (agora parcial) do índice activo, libertando o código
  --    e viatura+período para a nova versão.
  UPDATE public.contratos_renting
     SET substituido_em = now(),
         updated_by     = v_user_id
   WHERE id = v_old.id;

  -- 2) Cria a nova linha (clone, sem snapshots de total nem facturado_em)
  --    — herda o MESMO codigo da versão anterior (só a versao/badge muda).
  INSERT INTO public.contratos_renting (
    org_id, codigo, reserva_id, transferista_id, cliente_id, viatura_id, matricula, grupo,
    estacao_entrega_id, data_inicio, estacao_recolha_id, data_fim,
    estacao_origem_viatura_id,
    estado_operacional, estado_financeiro, origem, regime,
    tarifa_diaria, desconto_percentagem, taxa_iva, valor_total_manual,
    is_longa_duracao, renovacao_opcao, renovacao_intervalo_dias,
    franquia_valor, caucao_valor, kms_incluidos, km_adicional_valor,
    voucher_codigo, numero_processo, voo_referencia,
    local_entrega, local_recolha, comentarios_entrega, comentarios_recolha,
    observacoes, observacoes_internas,
    versao, contrato_anterior_id, motivo_versao,
    created_by
  )
  VALUES (
    v_old.org_id, v_old.codigo, v_old.reserva_id, v_old.transferista_id, v_old.cliente_id,
    v_old.viatura_id, v_old.matricula, v_old.grupo,
    v_old.estacao_entrega_id, v_old.data_inicio, v_old.estacao_recolha_id, v_old.data_fim,
    v_old.estacao_origem_viatura_id,
    v_old.estado_operacional, 'pendente', v_old.origem, v_old.regime,
    v_old.tarifa_diaria, v_old.desconto_percentagem, v_old.taxa_iva, v_old.valor_total_manual,
    v_old.is_longa_duracao, v_old.renovacao_opcao, v_old.renovacao_intervalo_dias,
    v_old.franquia_valor, v_old.caucao_valor, v_old.kms_incluidos, v_old.km_adicional_valor,
    v_old.voucher_codigo, v_old.numero_processo, v_old.voo_referencia,
    v_old.local_entrega, v_old.local_recolha, v_old.comentarios_entrega, v_old.comentarios_recolha,
    v_old.observacoes, v_old.observacoes_internas,
    v_old.versao + 1, v_old.id, p_motivo,
    v_user_id
  ) RETURNING id INTO v_new_id;

  -- 3) Copia condutores
  INSERT INTO public.contrato_condutores (
    org_id, contrato_id, cliente_id, motorista_id, is_principal
  )
  SELECT org_id, v_new_id, cliente_id, motorista_id, is_principal
    FROM public.contrato_condutores
   WHERE contrato_id = v_old.id;

  -- 4) Copia coberturas
  INSERT INTO public.contrato_coberturas (
    org_id, contrato_id, cobertura_id, cobertura_nome, preco_dia, franquia_valor
  )
  SELECT org_id, v_new_id, cobertura_id, cobertura_nome, preco_dia, franquia_valor
    FROM public.contrato_coberturas
   WHERE contrato_id = v_old.id;

  -- 5) Copia extras
  INSERT INTO public.contrato_extras (
    org_id, contrato_id, extra_id, extra_nome, preco_unidade, tipo_calculo, quantidade, total
  )
  SELECT org_id, v_new_id, extra_id, extra_nome, preco_unidade, tipo_calculo, quantidade, total
    FROM public.contrato_extras
   WHERE contrato_id = v_old.id;

  -- 6) Copia taxas
  INSERT INTO public.contrato_taxas (
    org_id, contrato_id, taxa_id, taxa_nome, percentagem, valor_fixo, base_calculo, valor_calculado
  )
  SELECT org_id, v_new_id, taxa_id, taxa_nome, percentagem, valor_fixo, base_calculo, valor_calculado
    FROM public.contrato_taxas
   WHERE contrato_id = v_old.id;

  RETURN v_new_id;
END;
$$;

COMMENT ON FUNCTION public.criar_versao_contrato_renting(uuid, text) IS
  'Cria uma nova versão de um contrato_renting copiando a linha actual + relações '
  '(condutores, coberturas, extras, taxas) e marcando a anterior como substituida. '
  'A nova versão herda o mesmo codigo da anterior — o numero do contrato nao muda '
  'ao editar, so a versao (fix 2026-07-14, ver 20260714130000).';
