-- ============================================================
-- Notas de Crédito — documento que credita (total ou PARCIAL)
-- uma cobrança/fatura já emitida, com motivo obrigatório.
-- ============================================================
-- Segue a MESMA mecânica das restantes peças da conta-corrente:
--   • notas_credito           — o documento (valor, motivo, numeração própria).
--   • trigger posta_movimento — gera um CRÉDITO em conta_movimentos (origem='nota_credito').
--   • anular a NC             — gera um DÉBITO de estorno.
--
-- Importante (contabilidade): a fatura original NÃO é anulada. A nota de
-- crédito ABATE-A — o saldo por creditar de uma cobrança é:
--     valor_total − Σ(notas de crédito ativas dessa cobrança)
-- Uma cobrança totalmente creditada continua 'emitida' (o crédito da NC
-- leva o saldo a 0). É o comportamento fiscal correto: o documento original
-- mantém-se e a NC compensa-o.
-- ============================================================

-- ------------------------------------------------------------
-- 1) Tabela notas_credito
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notas_credito (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          uuid NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE,
  codigo          bigint GENERATED BY DEFAULT AS IDENTITY,

  -- Documento original a creditar
  cobranca_id     uuid NOT NULL REFERENCES public.contrato_cobrancas(id) ON DELETE RESTRICT,
  -- A quem pertence o crédito (= destinatário da cobrança)
  entidade_id     uuid NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
  contrato_id     uuid REFERENCES public.contratos_renting(id) ON DELETE SET NULL,

  valor           numeric(10,2) NOT NULL CHECK (valor > 0),
  motivo          text NOT NULL,
  data_nota       date NOT NULL DEFAULT current_date,

  estado          text NOT NULL DEFAULT 'ativo' CHECK (estado IN ('ativo','anulado')),

  -- Sincronização Primavera (pronto para o ERP, tal como recibos/cobranças)
  documento_externo_ref   text,
  sincronizado_primavera  boolean NOT NULL DEFAULT false,

  created_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT notas_credito_codigo_org_unique UNIQUE (org_id, codigo)
);

CREATE INDEX IF NOT EXISTS idx_notas_credito_org      ON public.notas_credito (org_id);
CREATE INDEX IF NOT EXISTS idx_notas_credito_cobranca ON public.notas_credito (cobranca_id);
CREATE INDEX IF NOT EXISTS idx_notas_credito_entidade ON public.notas_credito (entidade_id);

-- ------------------------------------------------------------
-- 2) conta_movimentos: aceitar a nova origem + ligar à NC
-- ------------------------------------------------------------
ALTER TABLE public.conta_movimentos
  DROP CONSTRAINT IF EXISTS conta_movimentos_origem_check;
ALTER TABLE public.conta_movimentos
  ADD CONSTRAINT conta_movimentos_origem_check
  CHECK (origem IN ('cobranca','recibo','dano','ajuste','nota_credito'));

ALTER TABLE public.conta_movimentos
  ADD COLUMN IF NOT EXISTS nota_credito_id uuid
    REFERENCES public.notas_credito(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_conta_movimentos_nota_credito
  ON public.conta_movimentos (nota_credito_id) WHERE nota_credito_id IS NOT NULL;

-- ------------------------------------------------------------
-- 3) Validação (BEFORE INSERT): preenche org/entidade/contrato e
--    garante que a NC não excede o saldo por creditar da cobrança.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_nota_credito_valida()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_cob public.contrato_cobrancas%ROWTYPE;
  v_ja  numeric;
BEGIN
  -- FOR UPDATE: serializa NC concorrentes sobre a MESMA cobrança — sem o lock,
  -- duas NC simultâneas não veem o crédito uma da outra e podiam ultrapassar o saldo.
  SELECT * INTO v_cob FROM public.contrato_cobrancas WHERE id = NEW.cobranca_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Cobrança % não encontrada.', NEW.cobranca_id;
  END IF;

  -- A cobrança é a fonte de verdade do contexto: força org/entidade/contrato a
  -- partir dela (o crédito tem de ir para a conta da entidade efetivamente faturada).
  NEW.org_id      := v_cob.org_id;
  NEW.entidade_id := v_cob.destinatario_id;
  NEW.contrato_id := v_cob.contrato_id;

  IF v_cob.estado NOT IN ('emitida','paga') THEN
    RAISE EXCEPTION
      'Só é possível emitir nota de crédito sobre uma cobrança emitida ou paga (estado atual: %).',
      v_cob.estado;
  END IF;

  IF NOT v_cob.emite_fatura_fiscal THEN
    RAISE EXCEPTION
      'Nota de crédito só é aplicável a cobranças com fatura fiscal (cobrança interna não tem fatura a retificar).';
  END IF;

  SELECT COALESCE(SUM(valor), 0) INTO v_ja
    FROM public.notas_credito
    WHERE cobranca_id = NEW.cobranca_id AND estado = 'ativo';

  -- tolerância de 0,005 para arredondamentos
  IF NEW.valor > (v_cob.valor_total - v_ja) + 0.005 THEN
    RAISE EXCEPTION
      'Valor da nota de crédito (%) excede o saldo por creditar da cobrança (%).',
      NEW.valor, round(v_cob.valor_total - v_ja, 2);
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_nota_credito_valida ON public.notas_credito;
CREATE TRIGGER trg_nota_credito_valida
  BEFORE INSERT ON public.notas_credito
  FOR EACH ROW EXECUTE FUNCTION public.fn_nota_credito_valida();

-- ------------------------------------------------------------
-- 4) Posta o movimento na conta-corrente.
--    NC ativa  → CRÉDITO (abate a cobrança).
--    NC anulada → DÉBITO de estorno (reverte o crédito).
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.fn_nota_credito_posta_movimento()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.estado = 'ativo' THEN
      INSERT INTO public.conta_movimentos
        (org_id, entidade_id, data_movimento, tipo, valor, origem,
         nota_credito_id, cobranca_id, contrato_id, descricao)
      VALUES
        (NEW.org_id, NEW.entidade_id, NEW.data_nota, 'credito', NEW.valor, 'nota_credito',
         NEW.id, NEW.cobranca_id, NEW.contrato_id,
         'Nota de Crédito Nº ' || NEW.codigo || ' — ' || NEW.motivo);
    END IF;

  ELSIF TG_OP = 'UPDATE' AND OLD.estado = 'ativo' AND NEW.estado = 'anulado' THEN
    INSERT INTO public.conta_movimentos
      (org_id, entidade_id, tipo, valor, origem,
       nota_credito_id, cobranca_id, contrato_id, descricao)
    VALUES
      (NEW.org_id, NEW.entidade_id, 'debito', NEW.valor, 'nota_credito',
       NEW.id, NEW.cobranca_id, NEW.contrato_id, 'Estorno de nota de crédito anulada');
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_nota_credito_posta_movimento ON public.notas_credito;
CREATE TRIGGER trg_nota_credito_posta_movimento
  AFTER INSERT OR UPDATE OF estado ON public.notas_credito
  FOR EACH ROW EXECUTE FUNCTION public.fn_nota_credito_posta_movimento();

-- updated_at
CREATE OR REPLACE FUNCTION public.touch_notas_credito_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS trg_notas_credito_updated_at ON public.notas_credito;
CREATE TRIGGER trg_notas_credito_updated_at
  BEFORE UPDATE ON public.notas_credito
  FOR EACH ROW EXECUTE FUNCTION public.touch_notas_credito_updated_at();

-- ------------------------------------------------------------
-- 5) RLS — multi-tenant + acesso à faturação (igual a recibos)
-- ------------------------------------------------------------
ALTER TABLE public.notas_credito ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "mt_notas_credito_select" ON public.notas_credito;
DROP POLICY IF EXISTS "mt_notas_credito_insert" ON public.notas_credito;
DROP POLICY IF EXISTS "mt_notas_credito_update" ON public.notas_credito;

CREATE POLICY "mt_notas_credito_select" ON public.notas_credito
  FOR SELECT TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());

CREATE POLICY "mt_notas_credito_insert" ON public.notas_credito
  FOR INSERT TO authenticated
  WITH CHECK (
    (org_id IS NULL OR org_id = get_current_org_id())
    AND has_renting_faturacao_access()
  );

CREATE POLICY "mt_notas_credito_update" ON public.notas_credito
  FOR UPDATE TO authenticated
  USING (org_id = get_current_org_id() AND has_renting_faturacao_access());
-- sem DELETE: notas de crédito anulam-se (estado), não se apagam

COMMENT ON TABLE public.notas_credito IS
  'Notas de crédito (total ou parcial) sobre uma cobrança/fatura emitida. '
  'Cada NC ativa gera um crédito na conta-corrente da entidade (origem=nota_credito). '
  'A cobrança original mantém-se; saldo por creditar = valor_total − Σ(NC ativas).';
