-- supabase/migrations/20260724100000_acordos_pagamento.sql
-- ============================================================
-- Acordos de pagamento (parcelamento de faturas) — tabelas base
-- ============================================================
-- A dívida CONTINUA a ser a linha de `contrato_cobrancas`. Estas tabelas são
-- puro AGENDAMENTO: uma parcela não é uma cobrança e não tem caminho nenhum
-- para se tornar um documento de venda. É isto que impede dupla faturação por
-- construção, em vez de por disciplina de código.
--
-- Titular fiscal vs responsável operacional:
--   • titular_*      = destinatário da fatura original. IMUTÁVEL. É o NIF que
--                      vai em TODOS os recibos (exigência legal).
--   • responsavel_*  = quem assume o acordo, recebe avisos e leva o débito.
-- Um terceiro pode pagar a fatura de outrem; o recibo continua a ser emitido
-- ao titular. O seletor de entidade NUNCA altera o NIF do documento fiscal.
-- ============================================================

CREATE TABLE public.acordos_pagamento (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                  uuid NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE,
  codigo                  bigint GENERATED BY DEFAULT AS IDENTITY,

  cobranca_id             uuid NOT NULL REFERENCES public.contrato_cobrancas(id) ON DELETE RESTRICT,
  invoice_id              uuid REFERENCES public.invoices(id) ON DELETE SET NULL,

  -- Titular FISCAL (snapshot imutável do documento original)
  titular_id              uuid NOT NULL REFERENCES public.clientes(id) ON DELETE RESTRICT,
  titular_nome            text NOT NULL,
  titular_nif             text,

  -- Responsável OPERACIONAL (XOR — padrão de contrato_condutores)
  responsavel_cliente_id   uuid REFERENCES public.clientes(id) ON DELETE RESTRICT,
  responsavel_motorista_id uuid REFERENCES public.motoristas_ativos(id) ON DELETE RESTRICT,
  responsavel_papel        text NOT NULL
                           CHECK (responsavel_papel IN ('cliente','condutor','motorista')),
  responsavel_nome         text NOT NULL,

  valor_total             numeric(10,2) NOT NULL CHECK (valor_total > 0),
  frequencia              text NOT NULL
                          CHECK (frequencia IN ('semanal','mensal','personalizado')),
  dia_vencimento          smallint CHECK (dia_vencimento BETWEEN 1 AND 31),
  aviso_antecedencia_dias smallint NOT NULL DEFAULT 3
                          CHECK (aviso_antecedencia_dias BETWEEN 0 AND 30),

  estado                  text NOT NULL DEFAULT 'ativo'
                          CHECK (estado IN ('ativo','liquidado','incumprimento','cancelado')),
  cessao_aplicada         boolean NOT NULL DEFAULT false,
  precisa_revisao         boolean NOT NULL DEFAULT false,
  observacoes             text,

  created_by              uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT chk_acordo_responsavel_xor
    CHECK ((responsavel_cliente_id IS NULL) <> (responsavel_motorista_id IS NULL)),
  -- Papel e coluna preenchida têm de concordar: sem isto era possível gravar
  -- papel='motorista' apontando a um cliente, e os avisos iriam para o email errado.
  CONSTRAINT chk_acordo_papel_coerente
    CHECK ((responsavel_papel = 'motorista') = (responsavel_motorista_id IS NOT NULL)),
  CONSTRAINT acordos_pagamento_codigo_org_unique UNIQUE (org_id, codigo)
);

-- Uma dívida não pode ter dois acordos vivos ao mesmo tempo. É esta linha que
-- impede parcelar a mesma fatura duas vezes (a via mais provável para cobrar a dobrar).
CREATE UNIQUE INDEX uq_acordo_vivo_por_cobranca
  ON public.acordos_pagamento (cobranca_id)
  WHERE estado IN ('ativo','incumprimento');

CREATE INDEX idx_acordos_org_estado    ON public.acordos_pagamento (org_id, estado);
CREATE INDEX idx_acordos_resp_cliente  ON public.acordos_pagamento (responsavel_cliente_id)
  WHERE responsavel_cliente_id IS NOT NULL;
CREATE INDEX idx_acordos_resp_motorista ON public.acordos_pagamento (responsavel_motorista_id)
  WHERE responsavel_motorista_id IS NOT NULL;

CREATE TABLE public.acordo_parcelas (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id            uuid NOT NULL REFERENCES public.organizacoes(id) ON DELETE CASCADE,
  acordo_id         uuid NOT NULL REFERENCES public.acordos_pagamento(id) ON DELETE CASCADE,

  numero            smallint NOT NULL,   -- 0 = entrada, 1..N = parcelas
  data_vencimento   date NOT NULL,
  valor             numeric(10,2) NOT NULL CHECK (valor > 0),

  estado            text NOT NULL DEFAULT 'agendada' CHECK (estado IN (
                      'agendada', 'avisada', 'vencida',
                      'liquidacao_pendente',  -- dinheiro entrou, RC por confirmar
                      'paga',                 -- RC emitido com sucesso
                      'cancelada')),

  aviso_enviado_em  timestamptz,
  aviso_tentativas  smallint NOT NULL DEFAULT 0,
  aviso_erro        text,

  recibo_id         uuid REFERENCES public.recibos(id)  ON DELETE SET NULL,
  invoice_rc_id     uuid REFERENCES public.invoices(id) ON DELETE SET NULL,
  pago_em           timestamptz,

  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT acordo_parcelas_numero_unico UNIQUE (acordo_id, numero),
  -- Exige `recibo_id` e não `invoice_rc_id` porque uma cobrança com
  -- emite_fatura_fiscal = false não tem documento fiscal e não gera RC.
  -- Quando HÁ documento fiscal, a exigência de RC é imposta pelo fluxo:
  -- só `acordo_parcela_liquidar(p_invoice_id)` promove a parcela a 'paga'.
  CONSTRAINT chk_parcela_paga_tem_prova
    CHECK (estado <> 'paga' OR recibo_id IS NOT NULL)
);

CREATE INDEX idx_parcelas_acordo ON public.acordo_parcelas (acordo_id, numero);
CREATE INDEX idx_parcelas_vencimento ON public.acordo_parcelas (org_id, data_vencimento)
  WHERE estado IN ('agendada','avisada');

-- ── org_id herdado da cobrança (padrão de set_contrato_cobranca_org_id) ──
CREATE OR REPLACE FUNCTION public.set_acordo_org_id()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    SELECT org_id INTO NEW.org_id FROM public.contrato_cobrancas WHERE id = NEW.cobranca_id;
    IF NEW.org_id IS NULL THEN NEW.org_id := public.get_current_org_id(); END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_acordos_set_org_id
  BEFORE INSERT ON public.acordos_pagamento
  FOR EACH ROW EXECUTE FUNCTION public.set_acordo_org_id();

CREATE OR REPLACE FUNCTION public.set_parcela_org_id()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    SELECT org_id INTO NEW.org_id FROM public.acordos_pagamento WHERE id = NEW.acordo_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_parcelas_set_org_id
  BEFORE INSERT ON public.acordo_parcelas
  FOR EACH ROW EXECUTE FUNCTION public.set_parcela_org_id();

CREATE TRIGGER trg_acordos_updated_at
  BEFORE UPDATE ON public.acordos_pagamento
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_parcelas_updated_at
  BEFORE UPDATE ON public.acordo_parcelas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── RLS ──────────────────────────────────────────────────────────────────
ALTER TABLE public.acordos_pagamento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acordo_parcelas   ENABLE ROW LEVEL SECURITY;

-- RESTRICTIVE: combina com AND sobre as permissivas, por isso nenhuma policy
-- de funcionalidade consegue, por engano, abrir leitura cross-org.
-- Obrigatória em toda a tabela com org_id (ver supabase/tests/rls_org_isolation.test.sql).
CREATE POLICY rls_org_isolation ON public.acordos_pagamento
  AS RESTRICTIVE FOR ALL TO authenticated
  USING (org_id = public.get_current_org_id())
  WITH CHECK (org_id IS NULL OR org_id = public.get_current_org_id());

CREATE POLICY rls_org_isolation ON public.acordo_parcelas
  AS RESTRICTIVE FOR ALL TO authenticated
  USING (org_id = public.get_current_org_id())
  WITH CHECK (org_id IS NULL OR org_id = public.get_current_org_id());

CREATE POLICY "mt_acordos_select" ON public.acordos_pagamento
  FOR SELECT TO authenticated USING (has_renting_faturacao_access());
CREATE POLICY "mt_acordos_insert" ON public.acordos_pagamento
  FOR INSERT TO authenticated WITH CHECK (has_renting_faturacao_access());
CREATE POLICY "mt_acordos_update" ON public.acordos_pagamento
  FOR UPDATE TO authenticated USING (has_renting_faturacao_access());
-- Sem DELETE: acordos cancelam-se por estado.

CREATE POLICY "mt_parcelas_select" ON public.acordo_parcelas
  FOR SELECT TO authenticated USING (has_renting_faturacao_access());
CREATE POLICY "mt_parcelas_insert" ON public.acordo_parcelas
  FOR INSERT TO authenticated WITH CHECK (has_renting_faturacao_access());
CREATE POLICY "mt_parcelas_update" ON public.acordo_parcelas
  FOR UPDATE TO authenticated USING (has_renting_faturacao_access());

-- Devedor motorista: acesso ao próprio acordo via motoristas_ativos.user_id.
CREATE POLICY "acordos_devedor_motorista_select" ON public.acordos_pagamento
  FOR SELECT TO authenticated
  USING (responsavel_motorista_id IN (
    SELECT id FROM public.motoristas_ativos WHERE user_id = auth.uid()
  ));

CREATE POLICY "parcelas_devedor_motorista_select" ON public.acordo_parcelas
  FOR SELECT TO authenticated
  USING (acordo_id IN (
    SELECT a.id FROM public.acordos_pagamento a
     WHERE a.responsavel_motorista_id IN (
       SELECT id FROM public.motoristas_ativos WHERE user_id = auth.uid()
     )
  ));

COMMENT ON TABLE public.acordos_pagamento IS
  'Acordo de parcelamento de uma dívida já faturada. As parcelas são agendamento; '
  'a dívida permanece em contrato_cobrancas e a liquidação passa por recibos.';
COMMENT ON COLUMN public.acordos_pagamento.titular_id IS
  'Destinatário da fatura original. IMUTÁVEL — é o NIF de todos os recibos.';
COMMENT ON COLUMN public.acordos_pagamento.responsavel_papel IS
  'cliente/condutor = registo de clientes; motorista = motoristas_ativos (TVDE).';
COMMENT ON COLUMN public.acordo_parcelas.estado IS
  'liquidacao_pendente = dinheiro recebido mas recibo fiscal ainda não confirmado. '
  'Só passa a paga quando o RC é emitido com sucesso.';
