-- Recuperada de supabase_migrations.schema_migrations (versão 20260728143633).
-- Foi aplicada em produção sem ficheiro correspondente no repositório — e é a
-- mais importante das 15 que faltavam: sem ela, um clone novo voltava a ter uma
-- sequência de códigos GLOBAL partilhada entre organizações.
--
-- ============================================================
-- Código sequencial POR ORGANIZAÇÃO em contratos_renting,
-- contratos_prestacao, reservas, recibos e notas_credito
-- ============================================================
-- Bug (mesma causa já corrigida em motoristas_ativos, ver
-- 20260630000003_motorista_codigo_por_org.sql): `codigo` era
-- BIGINT GENERATED BY DEFAULT AS IDENTITY — uma única sequência
-- GLOBAL partilhada por todas as orgs. Uma org nova (ex.: PREMIUM
-- RIDE) continuava a numeração de outra org (ex.: contrato nº 684
-- logo a seguir ao 683 da Década Ousada) em vez de começar em 1.
-- Em `reservas` isto já ia longe: PREMIUM RIDE e Década Ousada com
-- códigos completamente entrelaçados (52..826 vs 16..825).
--
-- Viola o requisito central do produto: organizações são tenants
-- completamente independentes entre si — nenhuma deve conseguir
-- inferir volume de negócio de outra pelos números que lhe saem.
--
-- Correção, igual à de motoristas_ativos:
--   1. Largar a IDENTITY (a sequência global fica órfã, inofensiva).
--   2. Garantir índice único COMPOSTO (org_id, codigo) — códigos
--      repetem-se entre orgs mas são únicos dentro de cada uma.
--      contratos_renting já tem o seu (parcial, respeita versões
--      activas); as restantes ganham um índice único total aqui.
--   3. Trigger BEFORE INSERT por tabela: codigo = MAX(codigo)+1
--      dentro da org (NULL -> 1), serializado com
--      pg_advisory_xact_lock por (tabela, org). Se `codigo` já vier
--      preenchido no INSERT (ex.: criar_versao_contrato_renting, que
--      herda o código da versão anterior de propósito), respeita-se
--      o valor dado.
--
-- Backfill: NENHUM nesta migração — feito à parte, controlado, só
-- para a Premium Ride (ver acompanhamento na conversa).
--
-- Idempotente: pode correr-se mais que uma vez sem efeito colateral.
-- ============================================================

-- ── contratos_renting ──────────────────────────────────────────
ALTER TABLE public.contratos_renting
  ALTER COLUMN codigo DROP IDENTITY IF EXISTS;

CREATE OR REPLACE FUNCTION public.set_contrato_renting_codigo_por_org()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'contratos_renting.org_id é obrigatório para gerar código por org';
  END IF;

  IF NEW.codigo IS NOT NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('contratos_renting_codigo:' || NEW.org_id::text)
  );

  SELECT COALESCE(MAX(codigo), 0) + 1
    INTO NEW.codigo
    FROM public.contratos_renting
   WHERE org_id = NEW.org_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contrato_renting_codigo_por_org ON public.contratos_renting;

CREATE TRIGGER trg_contrato_renting_codigo_por_org
  BEFORE INSERT ON public.contratos_renting
  FOR EACH ROW
  EXECUTE FUNCTION public.set_contrato_renting_codigo_por_org();

-- ── contratos_prestacao ────────────────────────────────────────
ALTER TABLE public.contratos_prestacao
  ALTER COLUMN codigo DROP IDENTITY IF EXISTS;

CREATE UNIQUE INDEX IF NOT EXISTS contratos_prestacao_codigo_org_unique
  ON public.contratos_prestacao (org_id, codigo);

CREATE OR REPLACE FUNCTION public.set_contrato_prestacao_codigo_por_org()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'contratos_prestacao.org_id é obrigatório para gerar código por org';
  END IF;

  IF NEW.codigo IS NOT NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('contratos_prestacao_codigo:' || NEW.org_id::text)
  );

  SELECT COALESCE(MAX(codigo), 0) + 1
    INTO NEW.codigo
    FROM public.contratos_prestacao
   WHERE org_id = NEW.org_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_contrato_prestacao_codigo_por_org ON public.contratos_prestacao;

CREATE TRIGGER trg_contrato_prestacao_codigo_por_org
  BEFORE INSERT ON public.contratos_prestacao
  FOR EACH ROW
  EXECUTE FUNCTION public.set_contrato_prestacao_codigo_por_org();

-- ── reservas ───────────────────────────────────────────────────
ALTER TABLE public.reservas
  ALTER COLUMN codigo DROP IDENTITY IF EXISTS;

CREATE OR REPLACE FUNCTION public.set_reserva_codigo_por_org()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'reservas.org_id é obrigatório para gerar código por org';
  END IF;

  IF NEW.codigo IS NOT NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('reservas_codigo:' || NEW.org_id::text)
  );

  SELECT COALESCE(MAX(codigo), 0) + 1
    INTO NEW.codigo
    FROM public.reservas
   WHERE org_id = NEW.org_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_reserva_codigo_por_org ON public.reservas;

CREATE TRIGGER trg_reserva_codigo_por_org
  BEFORE INSERT ON public.reservas
  FOR EACH ROW
  EXECUTE FUNCTION public.set_reserva_codigo_por_org();

-- ── recibos ────────────────────────────────────────────────────
ALTER TABLE public.recibos
  ALTER COLUMN codigo DROP IDENTITY IF EXISTS;

CREATE OR REPLACE FUNCTION public.set_recibo_codigo_por_org()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'recibos.org_id é obrigatório para gerar código por org';
  END IF;

  IF NEW.codigo IS NOT NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('recibos_codigo:' || NEW.org_id::text)
  );

  SELECT COALESCE(MAX(codigo), 0) + 1
    INTO NEW.codigo
    FROM public.recibos
   WHERE org_id = NEW.org_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_recibo_codigo_por_org ON public.recibos;

CREATE TRIGGER trg_recibo_codigo_por_org
  BEFORE INSERT ON public.recibos
  FOR EACH ROW
  EXECUTE FUNCTION public.set_recibo_codigo_por_org();

-- ── notas_credito ──────────────────────────────────────────────
ALTER TABLE public.notas_credito
  ALTER COLUMN codigo DROP IDENTITY IF EXISTS;

CREATE OR REPLACE FUNCTION public.set_nota_credito_codigo_por_org()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.org_id IS NULL THEN
    RAISE EXCEPTION 'notas_credito.org_id é obrigatório para gerar código por org';
  END IF;

  IF NEW.codigo IS NOT NULL THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(
    hashtext('notas_credito_codigo:' || NEW.org_id::text)
  );

  SELECT COALESCE(MAX(codigo), 0) + 1
    INTO NEW.codigo
    FROM public.notas_credito
   WHERE org_id = NEW.org_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_nota_credito_codigo_por_org ON public.notas_credito;

CREATE TRIGGER trg_nota_credito_codigo_por_org
  BEFORE INSERT ON public.notas_credito
  FOR EACH ROW
  EXECUTE FUNCTION public.set_nota_credito_codigo_por_org();
