// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// Lidos daqui, já cortados de espaços/quebras de linha — ver env.ts para o
// porquê (um \n no fim da chave partia o WebSocket do realtime em silêncio).
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
